// Run with Playwright installed and a static server at JATHIR_URL (default localhost:8000).
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const words = require('../../data/words.json');
(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/usr/bin/chromium', headless: true, args: ['--no-sandbox'] });
  const errors = [];
  try {
    const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
    page.on('pageerror', error => errors.push(error.message));
    const url = process.env.JATHIR_URL || 'http://127.0.0.1:8000';
    await page.goto(url);
    await page.waitForFunction(() => !document.querySelector('#start-daily').disabled);
    assert(await page.locator('#welcome-screen').isVisible());
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({path:'/tmp/jathir-mobile-home.png',fullPage:true});
    await page.click('#start-expert');
    assert.match(await page.locator('#difficulty').textContent(), /النخبة/);
    assert.equal(await page.locator('#practice-level').inputValue(), '4');
    const word = await page.locator('#word').textContent();
    const entry = words.find(w => w.word === word);
    assert.equal(entry.difficulty, 4);
    await page.click('#submit-guess');
    assert.match(await page.locator('#message').textContent(), /ثلاثة/);
    await page.click('[data-letter="ك"]');
    await page.click('#delete-letter');
    assert.equal(await page.locator('.tile.filled').count(), 0);
    for (const letter of entry.root) await page.click(`[data-letter="${letter}"]`);
    await page.keyboard.press('Enter');
    assert.match(await page.locator('#message').textContent(), /أحسنت/);
    assert(await page.locator('#root-story').isVisible());
    assert.equal(await page.locator('#submit-guess').isDisabled(), true);
    await page.click('#next-button');
    assert.notEqual(await page.locator('#word').textContent(), word);
    await page.selectOption('#practice-level', '1');
    assert.equal(await page.locator('#difficulty').textContent(), 'سهل');
    await page.click('#sound-button');
    await page.check('#reduce-motion');
    await page.check('#color-blind');
    await page.reload();
    await page.waitForFunction(() => !document.querySelector('#start-daily').disabled);
    assert.equal(await page.locator('#sound-button').getAttribute('aria-pressed'), 'false');
    assert.equal(await page.locator('#reduce-motion').isChecked(), true);
    assert.equal(await page.locator('#color-blind').isChecked(), true);
    await page.click('#start-daily');
    assert.equal(await page.locator('#practice-options').isVisible(), false);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({path:'/tmp/jathir-mobile-game.png',fullPage:true});
    await page.click('#help-button');
    assert(await page.locator('#help-dialog').isVisible());
    await page.keyboard.press('Escape');
    await page.click('#stats-button');
    assert(await page.locator('#stats-dialog').isVisible());
    await page.keyboard.press('Escape');
    await page.click('#back-home');
    assert(await page.locator('#welcome-screen').isVisible());
    await page.setViewportSize({width:320,height:740});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.click('#start-practice');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    const reduced = await browser.newPage({ reducedMotion:'reduce' });
    await reduced.goto(url);
    assert.equal(await reduced.locator('.ambient-pattern').evaluate(el=>getComputedStyle(el).animationName), 'none');
    assert.deepEqual(errors, []);
    console.log('Browser checks passed: mobile 320/390px, expert win, Enter, deletion, levels, next word, saved preferences, daily, dialogs, navigation and reduced motion.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
